# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=30)),
                ('moneys', models.CharField(max_length=30)),
                ('invitation', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
