# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_users_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='uni',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
