# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_consumption_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption_record',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consumption_record',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
