# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20170121_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='purchase_times',
            field=models.IntegerField(default=0),
        ),
    ]
