# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_users_purchase_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption_record',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
