# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_consumption_record_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption_record',
            name='create_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
