# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20170122_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption_record',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
