# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20170122_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='new_awards',
            field=models.IntegerField(default=30),
        ),
    ]
