# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_users_new_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='recharge_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('out_no', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pay', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Users')),
            ],
        ),
    ]
