# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_xgluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xgluser',
            name='telephone',
            field=models.CharField(max_length=30),
        ),
    ]
